#ifndef WICK_CORE_TYPES_H
#define WICK_CORE_TYPES_H

#define WICK_CORE_TYPE_MIN 0
#define WICK_CORE_TYPE_INT 0
#define WICK_CORE_TYPE_DOUBLE 1
#define WICK_CORE_TYPE_ARRAY 2
#define WICK_CORE_TYPE_ASSOC 3
#define WICK_CORE_TYPE_FUNC 4
#define WICK_CORE_TYPE_DYN 5
#define WICK_CORE_TYPE_MAX 5

#endif /* WICK_CORE_TYPES_H */
