#! /usr/bin/env python3
# encoding: utf-8

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.program(
                source = 'size_test.c',
                target = 'size_test',
                )

    bld.program(
                source = 'scratch.c',
                target = 'scratch',
                )

    #bld.program(
                #source = 'parse.c',
                #target = 'parse',
                #)

    bld.objects(
            source = 'hash.c',
            target = 'parser_objects',
            )

    bld.program(
            use = 'parser_objects',
            source = 'hash_tests.c',
            target = 'hash_tests',
            )

    bld.program(
            use = 'parser_objects',
            source = 'test.c',
            target = 'test',
            )

    bld.shlib(
        source = [
            'wick_core.c', 'wick_alloc.c', 'wick_place.c',
            'wick_channel.c', 'wick_globals.c', 'wick_dyn.c',
            'wick_string.c', 'wick_error.c', 'wick_equal.c', 'wick_array.c', 'wick_assoc.c'
            ],
        target = 'wick',
        libs = 'rt',
        )

    bld.program(
                source = 'type_system_test.c',
                target = 'type_system_test',
                use = 'wick',
                )
