#! /usr/bin/env python3
# encoding: utf-8

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.program(
                source = 'size_test.c', 
                target = 'size_test', 
                )

    bld.program(
                source = 'utf8_file_test.c', 
                target = 'utf8_file_test', 
                )

    bld.program(
                source = 'scratch.c', 
                target = 'scratch', 
                )

    bld.program(
                source = 'parse.c', 
                target = 'parse', 
                use = 'utf8proc',
                includes = ['.', '../deps/utf8proc'], 
                )
